apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672   # RabbitMQ default port
    targetPort: 5672
  - protocol: TCP
    port: 15672   # UI port
    targetPort: 15672
  type: ClusterIP

