global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node

  - job_name: 'nodejs-backend'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [kubernetes_pod_lable_add_here]
        action: keep
        regex: backend
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'mongodb'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [mangoDB_pod_lable_here]
        action: keep
        regex: mongodb
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'rabbitmq'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [rabbitMQ_pod_lable_goes_here]
        action: keep
        regex: rabbitmq
    scrape_interval: 15s
    metrics_path: /metrics
