apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snonrootuser
spec:
  crd:
    spec:
      names:
        kind: K8sNonRootUser
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snonrootuser

        violation[{"msg": msg}] {
          input.review.object.spec.containers[_].securityContext.runAsUser == 0   
          msg := "Running as root user is not allowed."
        }                                                                           #add the containers
